# Generated by Django 5.1 on 2024-11-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cisco',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dren',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
