CREATE TABLE public.tdb_ref (
  id SERIAL PRIMARY KEY,
  "CODE_ETAB" BIGINT,
  "NOM_ETAB" TEXT,
  "CODE_ZAP" INTEGER,
  "ZAP" TEXT,
  "CODE_CISCO" INTEGER,
  "CISCO" TEXT,
  "CODE_DREN" INTEGER,
  "DREN" TEXT,
  "REGION" TEXT,
  "DISTRICT" TEXT,
  "COMMUNE" TEXT,
  "FOKONTANY" TEXT,
  "MILIEU" TEXT,
  "SECTEUR" TEXT,
  "LATITUDE" NUMERIC,
  "LONGITUDE" NUMERIC,
  "ALTITUDE" NUMERIC,
  imported_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX idx_tdb_ref_code_etab ON public.tdb_ref ("CODE_ETAB");

ALTER TABLE public.tdb_ref ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tdb_ref read" ON public.tdb_ref FOR SELECT USING (true);